# Generated by Django 5.1.2 on 2024-10-24 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projcadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='tempo_de_serviço',
            new_name='tempo_de_servico',
        ),
    ]
